---
title: "Vegdist Demo"
output: html_notebook
---

# Demo of dsMicrobiomeClient

## Setup DataSHIELD's dsMicrobiomeClient package

### Requirements
- Opal  3.0.6 (server - service)
- opalr 1.5.0 (client - R Package)
- vegan 2.5-7 (server - R Package)

### Load packages
```{r}
library('DSI')
library('DSOpal')
library('dsBaseClient')
library('dsMicrobiomeClient')
```

### Login

```{r}
builder <- DSI::newDSLoginBuilder()

builder$append(server = "study", url = "http://192.168.56.100:8080", user = "administrator", password = "datashield_test&", table = "hackathon.data", driver = "OpalDriver")

logindata <- builder$build()
conns <- DSI::datashield.login(logins = logindata, assign = TRUE, symbol = "D")
```

### Setup data

```{r}
ds.ls(datasources=conns)

ds.dataFrame(c("D$breads", "D$cereals", "D$cheese", "D$coffee", "D$dairy", "D$spreads"), newobj="F")

ds.ls(datasources=conns)
```

## Demo sequence ds.vegdist_assign

```{r}
ds.vegdist_assign("F", newobj="A", datasources=conns)

ds.ls(datasources=conns)

ds.class("A", datasources=conns)
```
## Demo sequence ds.vegdist

```{r}
res <- ds.vegdist("F", datasources=conns)

print(res)
```

## Logout

```{r}
DSI::datashield.logout(conns)
```
